---
- name: import generic tasks
  import_tasks: common.yml

- name: include vars
  include_vars: vars/vars.yml

- name: install packages
  apt:
    name:
      - neutron-linuxbridge-agent
      - nova-compute
    state: latest

- name: configure nova
  ini_file:
    path: /etc/nova/nova.conf
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{password}}@rabbit" }
    - { section: "DEFAULT", option: "my_ip", value: "{{ansible_host}}" }
    - { section: "DEFAULT", option: "use_neutron", value: "true" }
    - { section: "DEFAULT", option: "firewall_driver", value: "nova.virt.firewall.NoopFirewallDriver" }
    - { section: "api", option: "auth_strategy", value: "keystone" }
    - { section: "vnc", option: "enabled", value: "True" }
    - { section: "vnc", option: "vncserver_listen", value: "0.0.0.0" }
    - { section: "vnc", option: "vncserver_proxyclient_address", value: "$my_ip" }
    - { section: "vnc", option: "novncproxy_base_url", value: "http://{{hostvars['nova']['public_ip']}}:6080/vnc_auto.html" }
    - { section: "glance", option: "api_servers", value: "http://glance:9292" }
    - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/nova/tmp" }
    - { section: "keystone_authtoken", option: "auth_uri", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://keystone:35357" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "keystone:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "nova" }
    - { section: "keystone_authtoken", option: "password", value: "{{password}}" }
    - { section: "placement", option: "os_region_name", value: "RegionOne" }
    - { section: "placement", option: "project_domain_name", value: "Default" }
    - { section: "placement", option: "project_name", value: "service" }
    - { section: "placement", option: "auth_type", value: "password" }
    - { section: "placement", option: "user_domain_name", value: "Default" }
    - { section: "placement", option: "auth_url", value: "http://keystone:35357" }
    - { section: "placement", option: "username", value: "placement" }
    - { section: "placement", option: "password", value: "{{password}}" }
    - { section: "neutron", option: "url", value: "http://neutron:9696" }
    - { section: "neutron", option: "auth_url", value: "http://keystone:35357" }
    - { section: "neutron", option: "auth_type", value: "password" }
    - { section: "neutron", option: "project_domain_name", value: "Default" }
    - { section: "neutron", option: "user_domain_name", value: "Default" }
    - { section: "neutron", option: "region_name", value: "RegionOne" }
    - { section: "neutron", option: "project_name", value: "service" }
    - { section: "neutron", option: "username", value: "neutron" }
    - { section: "neutron", option: "password", value: "{{password}}" }
  notify:
    - restart nova
- name: configure nova (delete some lines)
  ini_file: path=/etc/nova/nova.conf section={{item.section}} option={{item.option}} state=absent
  with_items:
    - { section: "DEFAULT", option: "log_dir" }
  notify:
    - restart nova

- name: configure neutron
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{password}}@rabbit" }
    - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
    - { section: "keystone_authtoken", option: "auth_uri", value: "http://keystone:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://keystone:35357" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "keystone:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "neutron" }
    - { section: "keystone_authtoken", option: "password", value: "{{password}}" }
- name: configure neutron l2 agent
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{item.section}}"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - { section: "linux_bridge", option: "physical_interface_mappings", value: "provider:ens5" }
    - { section: "vxlan", option: "enable_vxlan", value: "true" }
    - { section: "vxlan", option: "local_ip", value: "{{ansible_host}}" }
    - { section: "vxlan", option: "l2_population", value: "true" }
    - { section: "securitygroup", option: "enable_security_group", value: "true" }
    - { section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }
  notify:
    - restart neutron
