---
- hosts: neutron
  vars:
    password: zoblesmouches42
  tasks:
  - import_tasks: common.yml

  - name: install neutron
    apt: name={{item}} state=latest
    with_items:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
  - name: configure neutron
    ini_file: path=/etc/neutron/neutron.conf section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "database", option: "connection", value: "mysql+pymysql://neutron:{{password}}@mysql/neutron" }
      - { section: "DEFAULT", option: "core_plugin", value: "ml2" }
      - { section: "DEFAULT", option: "service_plugins", value: "router" }
      - { section: "DEFAULT", option: "allow_overlapping_ips", value: "true" }
      - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{password}}@rabbit" }
      - { section: "DEFAULT", option: "notify_nova_on_port_status_changes", value: "true" }
      - { section: "DEFAULT", option: "notify_nova_on_port_data_changes", value: "true" }
      - { section: "keystone_authtoken", option: "auth_uri", value: "http://keystone:5000" }
      - { section: "keystone_authtoken", option: "auth_url", value: "http://keystone:35357" }
      - { section: "keystone_authtoken", option: "memcached_servers", value: "keystone:11211" }
      - { section: "keystone_authtoken", option: "auth_type", value: "password" }
      - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
      - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
      - { section: "keystone_authtoken", option: "project_name", value: "service" }
      - { section: "keystone_authtoken", option: "username", value: "nova" }
      - { section: "keystone_authtoken", option: "password", value: "{{password}}" }
      - { section: "nova", option: "auth_url", value: "http://keystone:35357" }
      - { section: "nova", option: "auth_type", value: "password" }
      - { section: "nova", option: "project_domain_name", value: "Default" }
      - { section: "nova", option: "user_domain_name", value: "Default" }
      - { section: "nova", option: "region_name", value: "RegionOne" }
      - { section: "nova", option: "project_name", value: "service" }
      - { section: "nova", option: "username", value: "nova" }
      - { section: "nova", option: "password", value: "{{password}}" }
    notify:
      - restart neutron
  - name: configure neutron ml2
    ini_file: path=/etc/neutron/plugins/ml2/ml2_conf.ini section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "ml2", option: "type_drivers", value: "flat,vlan,vxlan" }
      - { section: "ml2", option: "tenant_network_types", value: "vxlan" }
      - { section: "ml2", option: "mechanism_drivers", value: "linuxbridge,l2population" }
      - { section: "ml2", option: "extension_drivers", value: "port_security" }
      - { section: "ml2_type_flat", option: "flat_networks", value: "provider" }
      - { section: "ml2_type_vxlan", option: "vni_ranges", value: "1:1000" }
      - { section: "securitygroup", option: "enable_ipset", value: "true" }
    notify:
      - restart neutron
  - name: configure neutron l2 agent
    ini_file: path=/etc/neutron/plugins/ml2/linuxbridge_agent.ini section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "linux_bridge", option: "physical_interface_mappings", value: "provider:ens5" }
      - { section: "vxlan", option: "enable_vxlan", value: "true" }
      - { section: "vxlan", option: "local_ip", value: "{{ansible_host}}" }
      - { section: "vxlan", option: "l2_population", value: "true" }
      - { section: "securitygroup", option: "enable_security_group", value: "true" }
      - { section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }
    notify:
      - restart neutron
  - name: configure neutron l3 agent
    ini_file: path=/etc/neutron/l3_agent.ini section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }
    notify:
      - restart neutron
  - name: configure neutron dhcp agent
    ini_file: path=/etc/neutron/dhcp_agent.ini section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }
      - { section: "DEFAULT", option: "dhcp_driver", value: "neutron.agent.linux.dhcp.Dnsmasq" }
      - { section: "DEFAULT", option: "enable_isolated_metadata", value: "true" }
    notify:
      - restart neutron
  - name: configure neutron metadata agent
    ini_file: path=/etc/neutron/metadata_agent.ini section={{item.section}} option={{item.option}} value={{item.value}}
    with_items:
      - { section: "DEFAULT", option: "nova_metadata_host", value: "nova" }
      - { section: "DEFAULT", option: "metadata_proxy_shared_secret", value: "{{password}}" }
    notify:
      - restart neutron

  - name: initiate neutron database
    shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron && touch /root/.ansible_initiate_neutron_db
    args:
      creates: /root/.ansible_initiate_neutron_db

  handlers:
  - name: restart neutron
    service:
      name: "{{item}}"
      state: restarted
    with_items:
      - "neutron-server"
      - "neutron-dhcp-agent"
      - "neutron-metadata-agent"
      - "neutron-l3-agent"
      - "neutron-linuxbridge-agent"
