---
- hosts: rabbit
  vars:
    password: zoblesmouches42
  tasks:
  - name: install rabbitmq-server
    apt: name=rabbitmq-server state=latest
  - name: check openstack user
    shell: rabbitmqctl list_users | grep -q openstack
    register: user
    ignore_errors: True
  - name: create rabbitmq openstack user
    command: rabbitmqctl add_user openstack {{ password }}
    when: user|failed
  - name: configure rights
    command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
    when: user|failed
